## CP
perl ~/ePerl/interleaved2pairs.pl -i CP_AGTCAA_prinseq_trimmed_clean_desc_paired_scr.fasta \
-f CP_AGTCAA_prinseq_trimmed_clean_desc_paired_scr_1.fasta \
-r CP_AGTCAA_prinseq_trimmed_clean_desc_paired_scr_2.fasta

seqtk sample -s11 CP_AGTCAA_prinseq_trimmed_clean_desc_paired_scr_1.fasta 1000000 > CP_AGTCAA_prinseq_trimmed_clean_desc_paired_scr_1_1m.fasta
seqtk sample -s11 CP_AGTCAA_prinseq_trimmed_clean_desc_paired_scr_2.fasta 1000000 > CP_AGTCAA_prinseq_trimmed_clean_desc_paired_scr_2_1m.fasta

~/apps/bin/shuffleSeqs-fast CP_AGTCAA_prinseq_trimmed_clean_desc_paired_scr_1_1m.fasta \
CP_AGTCAA_prinseq_trimmed_clean_desc_paired_scr_2_1m.fasta \
> CP_AGTCAA_prinseq_trimmed_clean_desc_paired_scr_2m_interl.fasta

## Dasyphyllum
perl ~/ePerl/interleaved2pairs.pl -i Dasyphllum_ATCACG_prinseq_trimmed_clean_desc_paired_scr.fasta \
-f Dasyphllum_ATCACG_prinseq_trimmed_clean_desc_paired_scr_1.fasta \
-r Dasyphllum_ATCACG_prinseq_trimmed_clean_desc_paired_scr_2.fasta

seqtk sample -s11 Dasyphllum_ATCACG_prinseq_trimmed_clean_desc_paired_scr_1.fasta 1000000 > Dasyphllum_ATCACG_prinseq_trimmed_clean_desc_paired_scr_1_1m.fasta
seqtk sample -s11 Dasyphllum_ATCACG_prinseq_trimmed_clean_desc_paired_scr_2.fasta 1000000 > Dasyphllum_ATCACG_prinseq_trimmed_clean_desc_paired_scr_2_1m.fasta

~/apps/bin/shuffleSeqs-fast Dasyphllum_ATCACG_prinseq_trimmed_clean_desc_paired_scr_1_1m.fasta \
Dasyphllum_ATCACG_prinseq_trimmed_clean_desc_paired_scr_2_1m.fasta \
> Dasyphllum_ATCACG_prinseq_trimmed_clean_desc_paired_scr_2m_interl.fasta

## Gerb
perl ~/ePerl/interleaved2pairs.pl -i Gerb_GGCTAC_prinseq_trimmed_clean_desc_paired_scr.fasta \
-f Gerb_GGCTAC_prinseq_trimmed_clean_desc_paired_scr_1.fasta \
-r Gerb_GGCTAC_prinseq_trimmed_clean_desc_paired_scr_2.fasta

seqtk sample -s11 Gerb_GGCTAC_prinseq_trimmed_clean_desc_paired_scr_1.fasta 1000000 > Gerb_GGCTAC_prinseq_trimmed_clean_desc_paired_scr_1_1m.fasta
seqtk sample -s11 Gerb_GGCTAC_prinseq_trimmed_clean_desc_paired_scr_2.fasta 1000000 > Gerb_GGCTAC_prinseq_trimmed_clean_desc_paired_scr_2_1m.fasta

~/apps/bin/shuffleSeqs-fast Gerb_GGCTAC_prinseq_trimmed_clean_desc_paired_scr_1_1m.fasta \
Gerb_GGCTAC_prinseq_trimmed_clean_desc_paired_scr_2_1m.fasta \
> Gerb_GGCTAC_prinseq_trimmed_clean_desc_paired_scr_2m_interl.fasta

## Gnaph
perl ~/ePerl/interleaved2pairs.pl -i Gnaph_ACAGTG_prinseq_trimmed_clean_desc_paired_scr.fasta \
-f Gnaph_ACAGTG_prinseq_trimmed_clean_desc_paired_scr_1.fasta \
-r Gnaph_ACAGTG_prinseq_trimmed_clean_desc_paired_scr_2.fasta

seqtk sample -s11 Gnaph_ACAGTG_prinseq_trimmed_clean_desc_paired_scr_1.fasta 1000000 > Gnaph_ACAGTG_prinseq_trimmed_clean_desc_paired_scr_1_1m.fasta
seqtk sample -s11 Gnaph_ACAGTG_prinseq_trimmed_clean_desc_paired_scr_2.fasta 1000000 > Gnaph_ACAGTG_prinseq_trimmed_clean_desc_paired_scr_2_1m.fasta

~/apps/bin/shuffleSeqs-fast Gnaph_ACAGTG_prinseq_trimmed_clean_desc_paired_scr_1_1m.fasta \
Gnaph_ACAGTG_prinseq_trimmed_clean_desc_paired_scr_2_1m.fasta \
> Gnaph_ACAGTG_prinseq_trimmed_clean_desc_paired_scr_2m_interl.fasta

## Saff
perl ~/ePerl/interleaved2pairs.pl -i Saff_GATCAG_prinseq_trimmed_clean_desc_paired_scr.fasta \
-f Saff_GATCAG_prinseq_trimmed_clean_desc_paired_scr_1.fasta \
-r Saff_GATCAG_prinseq_trimmed_clean_desc_paired_scr_2.fasta

seqtk sample -s11 Saff_GATCAG_prinseq_trimmed_clean_desc_paired_scr_1.fasta 1000000 > Saff_GATCAG_prinseq_trimmed_clean_desc_paired_scr_1_1m.fasta
seqtk sample -s11 Saff_GATCAG_prinseq_trimmed_clean_desc_paired_scr_2.fasta 1000000 > Saff_GATCAG_prinseq_trimmed_clean_desc_paired_scr_2_1m.fasta

~/apps/bin/shuffleSeqs-fast Saff_GATCAG_prinseq_trimmed_clean_desc_paired_scr_1_1m.fasta \
Saff_GATCAG_prinseq_trimmed_clean_desc_paired_scr_2_1m.fasta \
> Saff_GATCAG_prinseq_trimmed_clean_desc_paired_scr_2m_interl.fasta

## Senecio
perl ~/ePerl/interleaved2pairs.pl -i Senecio_TTAGGC_prinseq_trimmed_clean_desc_paired_scr.fasta \
-f Senecio_TTAGGC_prinseq_trimmed_clean_desc_paired_scr_1.fasta \
-r Senecio_TTAGGC_prinseq_trimmed_clean_desc_paired_scr_2.fasta

seqtk sample -s11 Senecio_TTAGGC_prinseq_trimmed_clean_desc_paired_scr_1.fasta 1000000 > Senecio_TTAGGC_prinseq_trimmed_clean_desc_paired_scr_1_1m.fasta
seqtk sample -s11 Senecio_TTAGGC_prinseq_trimmed_clean_desc_paired_scr_2.fasta 1000000 > Senecio_TTAGGC_prinseq_trimmed_clean_desc_paired_scr_2_1m.fasta

~/apps/bin/shuffleSeqs-fast Senecio_TTAGGC_prinseq_trimmed_clean_desc_paired_scr_1_1m.fasta \
Senecio_TTAGGC_prinseq_trimmed_clean_desc_paired_scr_2_1m.fasta \
> Senecio_TTAGGC_prinseq_trimmed_clean_desc_paired_scr_2m_interl.fasta

## TKS
perl ~/ePerl/interleaved2pairs.pl -i TKS_CAGATC_prinseq_trimmed_clean_desc_paired_scr.fasta \
-f TKS_CAGATC_prinseq_trimmed_clean_desc_paired_scr_1.fasta \
-r TKS_CAGATC_prinseq_trimmed_clean_desc_paired_scr_2.fasta

seqtk sample -s11 TKS_CAGATC_prinseq_trimmed_clean_desc_paired_scr_1.fasta 1000000 > TKS_CAGATC_prinseq_trimmed_clean_desc_paired_scr_1_1m.fasta
seqtk sample -s11 TKS_CAGATC_prinseq_trimmed_clean_desc_paired_scr_2.fasta 1000000 > TKS_CAGATC_prinseq_trimmed_clean_desc_paired_scr_2_1m.fasta

~/apps/bin/shuffleSeqs-fast TKS_CAGATC_prinseq_trimmed_clean_desc_paired_scr_1_1m.fasta \
TKS_CAGATC_prinseq_trimmed_clean_desc_paired_scr_2_1m.fasta \
> TKS_CAGATC_prinseq_trimmed_clean_desc_paired_scr_2m_interl.fasta